# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'mydocker'
        repository: 'ggonzales/testedotnet'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/SimpleAPI/Dockerfile'
        tags: |
          $(tag)    
- stage: Deploy
  dependsOn:
  - Build
  jobs:
  - deployment:
    displayName: Dev deploy
    environment: 
     name: Dev
     resourceType: VirtualMachine
     tags: dev
    strategy:
     runOnce:
       deploy:
         steps:
           - script: hostname
           - script: sudo docker ps -aq | xargs --no-run-if-empty sudo docker stop | xargs --no-run-if-empty sudo docker rm
           - script: sudo docker pull ggonzales/testedotnet:$(tag)
           - script: sudo docker images 
           #- script: |
           #   img=`sudo docker images | grep -i testedotnet | grep $(tag) | awk '{print $3}'`
           #   docker run -d ${img}
           #- script: docker run -d ggonzales/testedotnet:$(tag)
           - script: sudo docker run -d -p 80:80 -p 443:443 ggonzales/testedotnet:$(tag) --name "test-please-work"
           - script: sudo docker save ggonzales/testedotnet:$(tag) | gzip > testedotnet.tar.gz
             displayName: 'Dev based stage'
           - task: DownloadPipelineArtifact@2
             inputs:
               buildType: 'current'
               targetPath: '$(Pipeline.Workspace)'
           
           - task: PublishPipelineArtifact@1
             inputs:
              targetPath: '$(Pipeline.Workspace)'
              artifact: 'testedotnet.tar.gz'
              publishLocation: 'pipeline'
           - task: DownloadBuildArtifacts@1
             inputs:
              buildType: 'current'
              downloadType: 'specific'
              itemPattern: 'testedotnet*tar'
              downloadPath: '$(System.ArtifactsDirectory)'