# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'mydocker'
        repository: 'ggonzales/testedotnet'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/SimpleAPI/Dockerfile'
        tags: |
          $(tag)    
- stage: Deploy
  dependsOn:
  - Build
  jobs:
  - deployment:
    displayName: Dev deploy
    environment: Dev
    strategy:
     runOnce:
       deploy:
         steps:
           - script: sudo docker ps -aq | xargs sudo docker stop | xargs sudo docker rm
           - script: docker pull ggonzales/testedotnet:$(tag)
           - script: docker images 
           #- script: |
           #   img=`sudo docker images | grep -i testedotnet | grep $(tag) | awk '{print $3}'`
           #   docker run -d ${img}
           #- script: docker run -d ggonzales/testedotnet:$(tag)
           - script: docker run -d -p 80:80-p 443:443 ggonzales/testedotnet:$(tag) --name "test-please-work"
             displayName: 'Dev based stage'