# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/SimpleAPI/Dockerfile'
        tags: |
          $(tag)
- stage: InstallStage
  displayName: Install on My Docker Stage
  jobs:
    - job: InstallJob
      displayName: Intall on my docker job
      steps:
        - task: Docker@2
          inputs:
                containerRegistry: 'mydocker'
                #repository: 'ggonzales/testedotnet'
                command: buildAndPush
